baseURL: "https://rednafi.com"
languageCode: en
title: Redowan's Reflections
pluralizelisttitles: false

menu:
  pages:
    - name: Appearances
      url: /appearances/
      weight: 2
    - name: Maxims
      url: /maxims/
      weight: 4
    - name: Tags
      url: /tags/
      weight: 5

enableRobotsTXT: true
googleAnalytics: G-11NK905JK8
enableGitInfo: true

frontmatter:
  lastmod:
    - lastmod
    - :git
    - date

taxonomies:
  tag: tags

related:
  includeNewer: true
  threshold: 20
  toLower: true
  indices:
    - name: tags
      weight: 100
      type: basic
    - name: date
      weight: 10
      pattern: "2006"

minify:
  disableXML: true
  minifyOutput: true

pagination:
  pagerSize: 30

params:
  env: production
  author: "Redowan Delowar"

  social:
    twitter: rednafi

  schema:
    jobTitle: Software Engineer
    alternateName: rednafi
    image: "https://blob.rednafi.com/static/images/about/profile-2025.jpg"
    knowsAbout:
      - "Go"
      - "Python"
      - "Distributed Systems"
      - "Platform Engineering"
      - "Software Design"
    sameAs:
      - "https://github.com/rednafi"
      - "https://www.linkedin.com/in/rednafi/"
      - "https://bsky.app/profile/rednafi.com"
      - "https://x.com/rednafi"
      - "https://www.wikidata.org/wiki/Q139619919"
    websiteAlternateName:
      - "Redowan Delowar"
      - "Redowan Delowar's Blog"
      - "rednafi"
  description: >-
    Redowan Delowar — a roving amateur fumbling through software, systems, and sundry.

  DateFormat: "January 2, 2006"

  mainSections:
    - javascript
    - misc
    - zephyr
    - python
    - typescript
    - go
    - system

  notesSection: "shards"

  images: ["https://blob.rednafi.com/static/images/home/cover.png"]

  assets:
    favicon_svg: "/favicon.svg"
    favicon_png: "/favicon.png"

  analytics:
    google:
      SiteVerificationTag: "google-site-verification=GoibEK52o5Z7xpKQ7ppTd8bA_s1wQp5hcG7aIWPJJfk"
    yandex:
      SiteVerificationTag: "cb037a09f985e313"
    naver:
      SiteVerificationTag: "097e5d3cd7b9e1ee3ad0addb5aaeea1b1a50be20"

markup:
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: false
    tabWidth: 4

  goldmark:
    extensions:
      definitionList: true
      footnote: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "ArticlesRSS"]
  page: ["HTML"]
  section: ["HTML", "RSS"]
  taxonomy: ["HTML"]
  term: ["HTML", "RSS"]

services:
  rss:
    limit: 30

mediaTypes:
  application/articles+xml:
    suffixes:
      - xml

outputFormats:
  ArticlesRSS:
    mediaType: application/articles+xml
    baseName: articles
    isPlainText: false
    rel: alternate
    isHTML: false
    noUgly: true
    permalinkable: false

security:
  funcs:
    getenv:
      - "^HUGO_"
