name: Prettify code

on: push

jobs:
  prettify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install prettier

    - name: Run Prettier
      run: |
        npx prettier --write '**/*.js'
        npx prettier --write '**/*.css'

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Style: Prettify HTML and CSS'
