name: Lint check

on: push

jobs:
  prettify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - name: Run prettier on JS and CSS files
      uses: creyD/prettier_action@v4.3
      with:
          prettier_options: --check **/*.{js,css}

