name: Prettify code

on: push

jobs:
  prettify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install -g prettier

    - name: Run Prettier
      run: |
        find . -type f -name '*.css' | xargs prettier --write
        find . -type f -name '*.js' | xargs prettier --write

    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Lint"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
