name: Prettify code

on: push

jobs:
  prettify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - name: Install dependencies
      run: npm install -g prettier

    - name: Prettify code
      uses: creyD/prettier_action@v4.3
      with:
          prettier_options: --write **/*.{js,css}

    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Lint"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
